### PR TITLE
[MultiCopy] v2.0.0 allows for custom bulk duplication

### PR DESCRIPTION
**Pull request by melwyncarlo**
Thank you for creating a pull request to contribute to FreeCAD-macros!
To integrate your macro please make sure the following steps are complete:

- [X] Please check this box if you're not submitting a new macro.   
- [ ] Are you submitting a new macro ?  
- [ ] Have you followed the ['How to submit a macro'](../README.md#how-to-submit-a-macro) section of the README.md ?  
- [ ] Your macro has a [Description](../README.md#macro-description) in its header.  
- [ ] Your macro has a [CamelCase name](../README.md#camelcase-macro-name).  
- [ ] Your macro is named [appropriately](../README.md#macro-name-specifics).  
- [ ] Your macro contains a [Metadata section](../README.md#macro-metadata) that immediately follows the header description.  
- [ ] Your macro is Python3/Qt5 compliant and tested on the latest FreeCAD stable and development releases.  
- [ ] You're including documentation on how your macro works (bonus: screenshots and/or video on the Wiki)  
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)  
- [ ] Commit message is titled in the following way `[MacroName] Short description`.
- [ ] Optional, write or update the changelog in the macro, from latest to oldest.

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

This is MultiCopy v2.0.0. I have made all the changes requested. Furthermore, I've separated the file contents into modules, thereby leading to the creation of a MultiCopy package. So, now, you can use MultiCopy via GUI and CUI.

I've updated the Wiki accordingly, and have provided examples too.

[MultiCopy - Github Repository](https://github.com/melwyncarlo/MultiCopy)
[MultiCopy - FreeCAD Wiki Page](https://wiki.freecadweb.org/Macro_MultiCopy)
[MultiCopy - Forum Discussion](https://forum.freecadweb.org/viewtopic.php?f=22&t=56753)

You had suggested creation of modules for the 'AeroFoil' macro. If this is accepted, I'll modify the AeroFoil macro accordingly.

### CODE REVIEW

**Review by galou — CHANGES_REQUESTED** [review]
There is an issue with the diff. A few lines are shown side by side but most of the file appears as one big added chunk and one big removed chunk. Can you check whether the end of lines are consistent? Please use unix-style end of lines.

Please use only one directory for your macro: `multicopy` and put the ui and other non-importable files in the `multicopy/resource` subdirectory.

Isn't the `Conversion/MultiCopy/resources/MultiCopy.svg` an error?

**Comment by melwyncarlo** [comment]
That is correct. This is because I've deleted the originally merged files and folders, and have replaced them with the new ones. The multiple files contain the same contents (emended) as the original (single) file, but with bridges. that connect the files.

About the big added and removed chunk. It's got nothing to do on my part. Please have a look in this [image](https://i.ibb.co/BVfN74H/Screenshot-from-2021-03-24-08-01-32.png).
There is no large space, and this is from my forked FreeCAD repository that sent the pull request.

I have used just one directory. I have deleted the old directory and replaced it with the `MultiCopy` directory and its `resources` subdirectory.

No, the SVG is not an error. Because you asked for the icon to be placed alongside the `*.FCMacro` file, I did that; but I also kept one in the `resources` sub-directory so that the Python package may access it directly and safely (within the package direcotry itself).

**Comment by melwyncarlo** [comment]
Because Python is case-sensitive, and for convenience, I have kept the directory name the same as the macro name. Does it really need to be 'lower-case'?

**Comment by melwyncarlo** [comment]
Please do not merge this pull request. I have made some additional changes as requested, and would like to merge those changes. But before I merge, could you please confirm that the directory name `MultiCopy` is acceptable and that I do not have to use the lower-case variant `multicopy`. 

Also, the structure is as follows:

```
FreeCAD Macros /
     > MultiCopy.FCMacro
     > MultiCopy.svg
     > MultiCopy /
          > __init__.py
          > MultiCopyCore.py
          > MultiCopyGui.py
          > MultiCopyAuxFunc.py
          > resources /
               > MultiCopy.svg
               > MultiCopy_Main_Dialog.ui
               > MultiCopy_Commands_Dialog.ui
          > __pycache__ /
```

**Comment by melwyncarlo** [comment]
> There is an issue with the diff. A few lines are shown side by side but most of the file appears as one big added chunk and one big removed chunk. Can you check whether the end of lines are consistent? Please use unix-style end of lines.

If you check the line numbers in the **diff**, you'll see that there is no chunk: it goes from 95, then 96, 97, and somewhere at the bottom, 99 to 103, etc. The _diff_ is large because I've actually removed that whole chunk (compared to the former file) and put them in separate modules. That's why it shows a block of empty text. It's just for visual effects I think; it's not physically empty.

**Comment by galou** [comment]
Technically, the directory does not have to be lower case, it's just a Python convention. You know, as the main maintainer of this repository, I try to push things the way I like (respecting conventions though). I'll merge even if the directory is camel case because you do great work! And I thank you for it. To sum up, I let you the decision.

I get it with the diff. I'll pay more attention next time.

**Comment by melwyncarlo** [comment]
Thank you very much, Mr. Galou. I appreciate the feedback and the opportunity to post code to FreeCAD.
I'm used to C++, but I'm learning Python too, and its conventions on the go.
I've noted down your past suggestions and will use them as a guideline for future macros.

**Pull request closed without merging**
