### PR TITLE
[CenterOfMass]Use centerOfGravity instead of centerOfMass, corrections for part containers

### PR DESCRIPTION
**Pull request by chupins**
Littles corrections
- use centerOfGravity instead of centerOfMass
- a bounding box calculation is corrected for part containers not located at 0,0,0

### CODE REVIEW

**Comment by luzpaz** [comment]
Can you list the forum thread this is linked to ?

**Comment by chupins** [comment]
It's this thread : https://forum.freecadweb.org/viewtopic.php?f=24&t=31883
Should I put it in the MR text too ?

**Comment by luzpaz** [comment]
>It's this thread : https://forum.freecadweb.org/viewtopic.php?f=24&t=31883  

Thanks!

>  Should I put it in the MR text too ?

Unnecessary :wink:

**Comment by galou** [comment]
Thanks!

**Pull request merged**
