### PR TITLE
honeycomb_solid.py: fix typos 

### PR DESCRIPTION
**Pull request by luzpaz**
Fix source typo tickness->thickness and some other trivial typos

### CODE REVIEW

**Comment by galou** [comment]
Yes, it'll break compatibility. I would accept the change though but the macro version should be changed. Waiting for others to react...

**Comment by galou** [comment]
@luzpaz can you please increment the version? Then I'll merge.

**Comment by luzpaz** [comment]
@galou Looking at the source I'm at a loss on how to increment the version. I don't see an actual version number to increment.

**Comment by galou** [comment]
Sorry for the delay, have been really busy lately. The whole metadata are missing, I'll add them.

**Pull request merged**
