### PR TITLE
[Camera] tweaks to source formatting + grammar + definitions

### PR DESCRIPTION
**Pull request by luzpaz**
This PR introduces trivial changes to the source in way of grammar, code formatting and some readability tweaks. The chnages have been separated in to different commits for easier review. 

I'm not sure what mario52's github name is so i can CC him since he is essential to this review.

### CODE REVIEW

**Comment by luzpaz** [comment]
@chennes if you have a moment, I was wondering if you could provide feedback on how to prepare macros for the new metadata methodology?

**Comment by chennes** [comment]
Almost all macros in our repos are already using the expected metadata, though of course many of the lines are blank -- Camera is, though it doesn't have an icon specified.

**Comment by galou** [comment]
Can you set `__Version__ = '0.0.14'` and `__Icon__ = 'Camera.png'` please?

It would be also good to remove the `global var_name` for variables defined in the global scope as this is explicit, e.g. `pathFile  = ""` rather than `global pathFile ; pathFile  = ""` (ideally for this case `PATH_FILE = ''`, which is closer to PEP8).

**Comment by galou** [comment]
Thanks!

**Comment by luzpaz** [comment]
Lol, i wasn't finished :rofl:

**Comment by galou** [comment]
Sorry, please submit a new PR.

**Comment by luzpaz** [comment]
@galou i didn't ask permission from mario52 to change his macro. He's seems upset by the french to english changes as well. He also is reporting an error. So please revert this PR, if you don't mind?

**Comment by galou** [comment]
I would suggest that if mario52 doesn't agree with the changes he should decide to let us do some changes to the macro or we remove it from the repo.

**Pull request merged**
