### PR TITLE
python23 issue and subprocess pip install for ezdxf

### PR DESCRIPTION
**Pull request by goatchurchprime**
Python3 now requires list(dict.items()) to get a sortable list.

Also corrected the formatting back to how the author (who is also the one who has to debug it) prefers it.

Most importantly, added a function import_and_install(packagename) that does a subprocess ("pip", "install", packagename, "--user") that is used on ezdxf and works even when you are running an AppImage

Comments are in the forum seeking clarification as to the desirability (or alternative to) this missing-library solution.

### CODE REVIEW

**Comment by luzpaz** [comment]
Do you mind putting the name of macro in the commit summary for better git history recognition ?

**Comment by galou** [comment]
OK, I just realized that you, @goatchurchprime, are the author of this macro. I didn't get it from your post.

I'd like you to reconsider the formatting thing. If the macro is in a shared repository, the code should be written to make it the most understandable as possible for others and it should also try to respect conventions, especially PEP8. If you really insist on depepizing it, I'll merge, so please reconsider and comment.

**Comment by goatchurchprime** [comment]
> Do you mind putting the name of macro in the commit summary for better git history recognition ?

That request should probably go into the [front page instructions](https://github.com/FreeCAD/FreeCAD-macros#how-to-submit-a-macro).  The name is already on the branch, but you're saying to also put it at the start of every commit message in the branch?

**Comment by goatchurchprime** [comment]
> I'd like you to reconsider the formatting thing. If the macro is in a shared repository, the code should be written to make it the most understandable as possible for others and it should also try to respect conventions, especially PEP8. If you really insist on depepizing it, I'll merge, so please reconsider and comment.

I don't have a tall editor screen and my editor doesn't wordwrap -- one of the two justifications in PEP8 for short lines.  Allowing a very long lines is a good way to stop that g_dxf_colors list giving me a 250 headache in the middle of my file.  (Do you think it should be moved into its own data file?  I can't remember where I got it from right now.)  There are a few things like that, where function calls have a load of uninteresting parameters that I don't want wasting more vertical space than they deserve to.  

I could go on, but I'll stop myself.  In general, auto-formatting code is evil, because it takes the number of maintainers familiar with the code down from n=1 to n=0.  

I did check it out some of the stuff that happened, and the PEP8-izer that was used on it is not right.  For example, it changed:
`cen = p0 + lv*0.5 - lvperp*pf`
into:
`cen = p0 + lv * 0.5 - lvperp * pf`

The [PEP8 recommendations](https://www.python.org/dev/peps/pep-0008/#other-recommendations) state:
> If operators with different priorities are used, consider adding whitespace around the operators with the lowest priority(ies). Use your own judgment; however, never use more than one space, and always have the same amount of whitespace on both sides of a binary operator.
> Yes: 
`hypot2 = x*x + y*y`
> No: 
`hypot2 = x * x + y * y`

So I'd prefer to leave it as it is until we've addressed a few of the more important issues raised, such as:
 * the work-flow for maintaining, updating and publicizing these macros, 
 * some formal system for unit testing the macros to ensure their quality, 
 * properly handling dependencies of other python libraries (like ezdxf), 
 * when should macros be split into multiple files, and do they go in their own directory,
 * how to share basic functions between multiple macros.

**Comment by yorikvanhavre** [comment]
In any case I think we can merge this already, regardless of what happens next :)

**Pull request merged**
