### PR TITLE
[FCTree2Ascii] introduce last fork string + new style

### PR DESCRIPTION
**Pull request by 0penBrain**
@galou : you should wait some time so a new macro is stable before making cosmetic changes in it and not notifying the author. This makes it super boring to improve/maintain. :/
BTW : PEP8 tells that [constants are all caps](https://www.python.org/dev/peps/pep-0008/#constants) ;)

### CODE REVIEW

**Comment by luzpaz** [comment]
@0penBrain in @galou's defense, we're still trying to figure out a standard for this repo. Some macro devs are touch and go and others (a minority) are more active. I think eventually we'll 'nail down' a workflow where macro devs will be notified via PR when a macro is changed (not by them)

**Comment by 0penBrain** [comment]
@luzpaz I'm aware how much effort it takes to maintain and improve this repo, and am totally respectful to that. But I dare to state my opinion.
IMO, such kind of things will completely discourage authors to maintain their macros.
Also changing name of macro should be considered with much much care as it creates duplicate entries in the addon manager under 2 different names. This makes it not readable for user.
I'm a bit tired of all that ATM and till things here got a sharp definition, my choice will go to use only the forum & the wiki and not push anymore my macros to GH. ;)

**Comment by galou** [comment]
@OpenBrain: I'm sorry about this misunderstanding. I warned you that I would make some changes and supposed that you would take the Github version as main version. I neglected warning you that I indeed did some cosmetic changes and I see that your last modification are not based on my version. What disturbed me the most was the macro name (especially the `FC` in front of it). I didn't want to be too rude to ask for this change so I did the change myself. I take this as a lesson and will refuse a name that don't respect the standard of this repository. Another mistake I did, is that I forgot about the duplication in the Addon-Manager. The Addon-Manager takes the Github version in favor of the Wiki version only if the names are exactly the same and I forgot this when changing the name.

What I propose to you is:
- the new name will be `Information/TreeToAscii.FCMacro` preferably but `Information/Tree2Ascii.FCMacro` is also OK. The Wiki should be updated accordingly.
- the content will be entirely yours and I'll do the cosmetic changes if you wish me to.

If it's not OK with you, I'll remove the macro from this repository for now, even if I think that this is a nice macro.

**Comment by galou** [comment]
@OpenBrain: and thanks for the hint about constant in capitals, I actually didn't know this.

**Comment by 0penBrain** [comment]
@galou : I have to encourage you to be rude (let's say "straight") as a maintainer of this repo. I think it's far better to (respectfully :p ) reject a macro because it doesn't match some criteria than accept it then silently make changes. ;) Of course better if all the rules that need to be complied to can be found somewhere before doing the PR.
Go for your preferred macro name & location. ;) I'll try to update the wiki. Please do not directly make (cosmetic) changes inside the file. I prefer you add comments on GH or forum. So I can improve and take occasion of upgrades to take into account. Thx

**Comment by 0penBrain** [comment]
PR updated according @galou proposal

**Pull request merged**
