### PR TITLE
[CenterOfMass] Added support to enter a mass explicitly

### PR DESCRIPTION
**Pull request by nexx512**
Thank you for creating a pull request to contribute to FreeCAD-macros!
To integrate your macro please make sure the following steps are complete:

- [x] Please check this box if you're not submitting a new macro.   
- [ ] Are you submitting a new macro ?  
- [ ] Have you followed the ['How to submit a macro'](../README.md#how-to-submit-a-macro) section of the README.md ?  
- [ ] Your macro has a [Description](../README.md#macro-description) in its header.  
- [ ] Your macro has a [CamelCase name](../README.md#camelcase-macro-name).  
- [ ] Your macro is named [appropriately](../README.md#macro-name-specifics).  
- [ ] Your macro contains a [Metadata section](../README.md#macro-metadata) that immediately follows the header description.  
- [ ] Your macro is Python3/Qt5 compliant and tested on the latest FreeCAD stable and development releases.  
- [ ] You're including documentation on how your macro works (bonus: screenshots and/or video on the Wiki)  
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)  
- [ ] Commit message is titled in the following way `[MacroName] Short description`.
- [ ] Optional, write or update the changelog in the macro, from latest to oldest.

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by nexx512** [comment]
This pull request is a follow up to #130 with corrections mentioned in https://github.com/FreeCAD/FreeCAD-macros/pull/130#issuecomment-1113411721

**Comment by s-quirin** [comment]
Thank you for your contribution! I have a few comments and inconsistencies:
- [ ] You could already merge your part with #129
- [ ] Save (as) was a compromise with @chupins. "Transfer" is also okay, I even more like "to Doc.". You could also think about the icon then, e.g. Std_MergeProjects.svg
- [ ] Material density has a physical range, mass has not. How do you want to adjust the decimals in your spin box accordingly? The scientific notation is probably the better one to cover multiple order of magnitude.
- [ ] Your implementation affects Import and Export. You could think about having a Material "fixed mass" instead of checkbox.
- [ ] The density should change accordingly if you change mass, or the colouring should be disabled for this solid.

**Comment by nexx512** [comment]
* Having a "fixed mass" in the dropdown seems to be a reasonable alternative to a checkbox. I can check if I can do that.
* I didn't notice that the spinbox was limited to 99.99... There needs to be a better option. Maybe I check for reasonable ranges.
* I didn't look into the import and export feature...totally missed that.

**Comment by nexx512** [comment]
ok, I tried to refactor my changes but with no luck.
The design of this macro is way too complicated to be able to see what is happening. For example the spinDens is taken out of the SolidWidget object and manipulated in many other places. It's very hard to keep track of the paces in the code that need to be considered when a change is made. It's only 1000 lines of code but I wasn't able to find a clear structure, so I gave up. Sorry, but i guess this macro should be refactored with a clear and understandable architecture.

**Pull request closed without merging**
