### PR TITLE
[CenterOfMass] Fix Bugs and Regressions, improve customizability

### PR DESCRIPTION
**Pull request by s-quirin**
[X] Please check this box if you're not submitting a new macro.
---
Changelog:
- Deleted unused icon files
- Code: changed naming of preferences from global variables to constants (strict reading style guide given to #126)
- Bugfix: Message Boxes could not be used when not running FreeCAD on primary screen in a multimonitor setup
- Fixed regression: Startup Dialog using the new Message Box
- Bugfix: More than one Mesh was not calculated correctly
- Feature reinserted: Bounding Box (regression from #126)
- Feature added: Setting to color spheres
- Feature added: Setting to change color maps
- GUI: Update calculation added, Total density added, small rearrangement

### CODE REVIEW

**Comment by chupins** [comment]
Reminder for @galou : you've already check almost everything here when you reviewed #128

**Comment by s-quirin** [comment]
@galou This feature set is "beta" or even "stable" now, by all means ready for release.

**Comment by galou** [comment]
@s-quirin which feature are you talking about?

**Comment by galou** [comment]
Thanks for your contribution and your patience!

**Pull request merged**
