### PR TITLE
added some recompute() to make it work in FreeCAD 0.19

### PR DESCRIPTION
**Pull request by chbergmann**

### CODE REVIEW

**Comment by luzpaz** [comment]
@chbergmann thank. FYI please make the PR title a little more friendly for the admins. I had to dig to figure out that this updates the BoxCreator macro. 

So please revise the git commit itself and repush it   
to something like:  
`[BoxCreator] Made macro v0.19 compatible`   

Also I notice that the macro doesn't have a metadata header per
https://github.com/FreeCAD/FreeCAD-macros/#guidelines-for-submitting-a-macro (section 4). Could you add one and then bump the version because of this update?  
Thanks!

**Comment by chbergmann** [comment]
The BoxCreator macro was splitted into 3 files. I have merged them together into a single file boxcreator.FCMarco

**Comment by galou** [comment]
Why did you merge the files? The split allows to import `boxcreator` and use it as a library without a GUI. I think that this is a very good practice to separate GUI stuff from the core functions. The Addon-Manager has no problem with installing and removing related files, as long as they are listed in the metadata (`__Files__`).

**Comment by chbergmann** [comment]
I merged the files because luzpaz complained that the boxcreator.py has no metadata header. The metadata header is in BoxCreator.FCMacro. One file makes it easier for you to handle.

**Comment by chbergmann** [comment]
What do you think about adding some documentation for a macro (Readme.md with screenshots) also to this repository ? In the moment I have some docu in a different repo: https://github.com/chbergmann/boxcreator

**Comment by luzpaz** [comment]
@chbergmann sorry for the misunderstanding. We have an infrastructure quirk where we query the wiki via the addon manager for macros as well. Your suggestion is not a bad one, it merits further discussion for sure.

**Comment by chbergmann** [comment]
no problem. I leave the macro docu somewhere else on github.
I have deleted this branch and created a new one with a new pull request. Hope this will be good for merging.

**Pull request closed without merging**
