### PR TITLE
[AeroFoil] v2.0.0 creates airfoils in a custom manner.

### PR DESCRIPTION
**Pull request by melwyncarlo**
The 'AeroFoil' macro creates airfoil curves and faces using pre-defined models, algebraic functions, and DAT or CSV Files.

[AeroFoil - Github Repository](https://github.com/melwyncarlo/AeroFoil)
[AeroFoil - FreeCAD Wiki Page](https://wiki.freecadweb.org/Macro_AeroFoil)
[AeroFoil - Forum Discussion](https://forum.freecadweb.org/viewtopic.php?f=22&t=56162)

### CODE REVIEW

**Comment by melwyncarlo** [comment]
I'm made all the requested changes as per this link: [AeroFoil FORMER Pull Request](https://github.com/FreeCAD/FreeCAD-macros/pull/93)

**Comment by melwyncarlo** [comment]
I don't think backward-compatibility applies to my macro (at the moment). Because the dynamic properties are read-only, they cannot be changed (if they could've been changed, I suppose it'd give rise to a plethora of errors).
However, I chose the v2.0 keeping in mind that I had changed the Final_Dialog UI, the dynamic properties. I've also overhauled a function and broken it down into 4 separate functions, whilst adding a new feature. It seemed like a major change. The Macro file increased by about 40 kB.

**Comment by galou** [comment]
I'll need to investigate this. I'm sure that the creation of necessary folders was working in the Addon Manager. This may be due to the backslashes in the `__Files__` variable... Can you commit a version with `__Files__` defined on a single line? Thanks!

**Comment by melwyncarlo** [comment]
It still doesn't download the folder.

**Comment by galou** [comment]
I don't understand. For you to be able to test this, the change must first be merged in this repo. How did you test it? I just installed you macro with the Addon Manager and everything seems to be there ( I just tested the first dialog).

**Comment by melwyncarlo** [comment]
Oh, I thought you had merged it on Thursday, given the email _"Merged #96 into master."_ So I had tested it immediately, but to no avail then. If there were any other changes than the ones you had mentioned (in the latest merge), it would be the changes as directed by [LGTM](https://lgtm.com/) to get the alerts down to 0.

Regardless, I tested the process again: uninstall macro, relaunch FreeCAD, install macro, and relauch again, after which I launched the macro. The folder was still not downloaded. I wondered why. Then it hit me, maybe I should heed the warning from the `Report View` panel :  `GitPython not installed!  Cannot retrieve macros from git`, which I had been ignoring until now. 

Upon doing a `pip install GitPython` on my command terminal, and then testing the process again, it actually worked! The folder was finally downloaded alongside the macro. I believe that message showing up as **just a warning** is **misleading**. It should be an **ERROR**, because it affects the functioning of the macros.

The other users should be alerted should they face a [similar problem](https://forum.freecadweb.org/viewtopic.php?f=3&t=45592).

**Pull request merged**
